# Generated by Django 5.1.1 on 2024-10-26 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('date', models.DateTimeField(verbose_name='Желаемая дата получения')),
                ('service', models.CharField(choices=[('main', 'общий клининг'), ('general', 'генеральная уборка'), ('post-build', 'послестроительная уборка'), ('carpent', 'химчистка ковров и мебели'), ('other', 'иная услуга')], default='main', max_length=50, verbose_name='Услуга')),
                ('other_service', models.TextField(blank=True, null=True, verbose_name='Описание иной услуги')),
                ('status', models.CharField(choices=[('in-work', 'в работе'), ('completed', 'выполнено'), ('canceled', 'отменено')], default='in-work', max_length=50, verbose_name='Статус')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
